// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, KvCache, Logger, MRNObject, Queue, ServiceStub, SmartSql, Tracer,  } from '@liquidmetal-ai/raindrop-framework';
type SqlDb = {
  query: (sql: string, params?: unknown[]) => Promise<any[]>;
  execute: (sql: string, params?: unknown[]) => Promise<any>;
};

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  AI_ANALYSIS: ServiceStub<import('../ai-analysis/index.js').default>;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  ANTHROPIC_API_KEY: string;
  API_GATEWAY: ServiceStub<import('../api-gateway/index.js').default>;
  FINANCIAL_DB: SqlDb;
  FRONTEND_URL: string;
  logger: Logger;
  mem: KvCache;
  PLAID_CLIENT_ID: string;
  PLAID_ENVIRONMENT: string;
  PLAID_SECRET: string;
  SESSION_CACHE: KvCache;
  SESSION_SECRET: string;
  tracer: Tracer;
  TRANSACTION_PROCESSING_QUEUE: Queue<import('../transaction-processor/index.js').Body>;
  TRANSACTION_SYNC_QUEUE: Queue<import('../transaction-sync/index.js').Body>;
}
